### 获取token
POST http://localhost:8088/admin/login
Content-Type: application/json

// admin
// productAdmin 产品管理员
{
  "username": "productAdmin",
  "password": "banyuan"
}

> {% client.global.set("auth_token", response.body.data.token); %}

### 使用授权的token访问接口
### 获取用户菜单
GET http://localhost:8088/admin/info
Authorization: Bearer {{auth_token}}

###

### 商品列表查询
GET http://localhost:8088/product/list?pageNum=1&pageSize=5
Authorization: Bearer {{auth_token}}

###

### 订单查询
GET http://localhost:8088/order/list?pageNum=1&pageSize=10
Authorization: Bearer {{auth_token}}

###


### 营销，秒杀查询
GET http://localhost:8088/flash/list?pageNum=1&pageSize=5
Authorization: Bearer {{auth_token}}

###


### 用户管理
GET http://localhost:8088/role/listAll
Authorization: Bearer {{auth_token}}

###


